# -*- coding: utf-8 -*-
"""ืnew.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ycOytdlBtHnClHC1NM-NVK_4eVxWAtGu
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -U ultralytics

from ultralytics import YOLO

model = YOLO("yolov8s.pt")
model.train(data="/content/drive/MyDrive/roboflow/data.yaml", imgsz=640, epochs=150)

import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding

!cp -r runs/detect/train7 /content/drive/MyDrive/2ND\ YEAR/2/ROBOTIC\ LAB/project